name: OS image

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build image
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      # Runs the Super-Linter action
      - name: Build deployment
        run: |
          source $HOME/.poetry/env
          ./deploy/setup.sh

      - name: Upload deployment
        uses: actions/upload-artifact@v2
        with:
          name: raspios-lite.img
          path: raspios-lite.img
